[package]
name = "day-05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }
nom = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
divan = { workspace = true }
dhat = { workspace = true }

[[bench]]
name = "day-05"
path = "benches/benchmarks.rs"
harness = false

[[bench]]
name = "day-05-criterion"
path = "benches/benchmarks-criterion.rs"
harness = false

[features]
dhat-heap = []
